name: dartify
description: A Spotify API wrapper, written in Dart.
version: 0.0.2
#homepage: https://www.example.com
#author: Josh Feltimo <jfeltimo@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  json_object: ^1.0.19
  js: ^0.6.0

dev_dependencies:
  test: ^0.12.0
